apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintainerd
  labels:
    app: maintainerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainerd
  template:
    metadata:
      labels:
        app: maintainerd
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: ghcr.io/robertkielty/maintainerd:latest
          imagePullPolicy: Always
          args:
            - "-addr=:2525"
            - "-db-driver=$(MD_DB_DRIVER)"
            - "-db-dsn=$(MD_DB_DSN)"
            - "-fossa-token-env=FOSSA_API_TOKEN"
            - "-org=$ORG"
            - "-repo=$REPO"
          ports:
            - name: http
              containerPort: 2525
          envFrom:
            - secretRef:
                name: maintainerd-bootstrap-env
            - secretRef:
                name: maintainerd-db-env
            - secretRef:
                name: maintainerd-server-env
