apiVersion: batch/v1
kind: Job
metadata:
  name: maintainerd-migrate-schema
  namespace: maintainerd
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: maintainer-sync
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: migrate
        image: ghcr.io/robertkielty/maintainerd-migrate:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: maintainerd-db-env
        resources: {}
