apiVersion: v1
kind: Service
metadata:
  name: maintainerd-web
  labels:
    app: maintainerd-web
spec:
  selector:
    app: maintainerd-web
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
