apiVersion: v1
kind: Service
metadata:
  name: maintainerd-web-bff
  labels:
    app: maintainerd-web-bff
spec:
  selector:
    app: maintainerd-web-bff
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
