apiVersion: maintainer-d.cncf.io/v1alpha1
kind: CodeScannerSnyk
metadata:
  labels:
    app.kubernetes.io/name: code-scanners
    app.kubernetes.io/managed-by: kustomize
  name: zot-snyk
  namespace: code-scanners
spec:
  projectName: zot
