apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kdp-ws-operator-kcp-client
spec:
  secretName: kdp-ws-operator-kcp-client-cert
  duration: 8760h0m0s # 365 days
  renewBefore: 720h # 30 days
  commonName: "kdp-ws-operator"
  usages:
    - client auth
  issuerRef:
    name: ${CA_ISSUER_NAME}
