apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maintainerd-prod
  namespace: argocd
spec:
  project: maintainerd
  source:
    repoURL: https://github.com/robertkielty/maintainerd
    targetRevision: HEAD
    path: deploy/helm/maintainerd
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: maintainerd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
