apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: maintainer-d.cncf.io
spec:
  resources:
  - group: maintainer-d.cncf.io
    name: auditlogs
    schema: v251021-51dd08b.auditlogs.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: collaborators
    schema: v251021-51dd08b.collaborators.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: companies
    schema: v251021-51dd08b.companies.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: maintainers
    schema: v251021-51dd08b.maintainers.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: onboardingtasks
    schema: v251021-51dd08b.onboardingtasks.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: projectmemberships
    schema: v251021-51dd08b.projectmemberships.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: projects
    schema: v251021-51dd08b.projects.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: reconciliationresults
    schema: v251021-51dd08b.reconciliationresults.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: services
    schema: v251021-51dd08b.services.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceteams
    schema: v251021-51dd08b.serviceteams.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceusers
    schema: v251021-51dd08b.serviceusers.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceuserteams
    schema: v251021-51dd08b.serviceuserteams.maintainer-d.cncf.io
    storage:
      crd: {}
status: {}
