apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - cluster-role-aggregated.yaml
  - cluster-role-resources.yaml
  - cluster-role-configmap.yaml
