apiVersion: ENC[AES256_GCM,data:4Ro=,iv:D8YgXmPjSH0krihOnlZ++7qsh0aIgCC2YtiODmNf0QA=,tag:nyOPi7KRVkHmHR7G4XZB1Q==,type:str]
kind: ENC[AES256_GCM,data:cKG451EW,iv:eJ7xZHjCdchVvycEzvrcH0x+FCRFTwVqDG49vGj3vQA=,tag:i0vdjB6dWgM963hhRI+bHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8rUURreCqJtDs6BqK/xTk4yPqw==,iv:LLKDdXx7dVkhgnG/Zs5zyUMLxH+7O5zqQqr5SaLI0Lw=,tag:iZpqcKzTcTQGELHyvLdXag==,type:str]
    namespace: ENC[AES256_GCM,data:FhIJ+z9Ty5ZNOBs=,iv:TAajeZoMqgy4ur36AjEzcu5bwaf/FpdBBimTfO5N44k=,tag:MocJXSUEW1A2aCkq7b/lbg==,type:str]
type: ENC[AES256_GCM,data:hnjNsUk0,iv:f1lzllId1jDSVzk70YZATA+lQdD7TFeYgyZOK7shpYQ=,tag:Hy3uvwte9RHcKpXfLtXMPA==,type:str]
stringData:
    NEXT_PUBLIC_BFF_BASE_URL: ENC[AES256_GCM,data:nyIH7p8tBHno23JKdXj+g5yajkS9+PDXNLX/yQ==,iv:kPv316G50VWmuWjOjM4W0gwCD3Lv4LLPnCkGp+Exc24=,tag:Kfd20JojpxXzap2X/uq7pw==,type:str]
sops:
    age:
        - recipient: age13ky20ttewhjkjncjkj3xk4ngah6luurk7xu83p6w7f9z4r49js9qk2t3w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VloxNnVjZDFoMHkyWnZt
            MDR6SnVBcm9KU3dzSE0zeXVicHF4a0M2RkJrCmlDUDVMQUllcEE4SlVQR3k4WGUw
            NUhrR1k2UG1CYzFxUFJPRDNybC9aUDAKLS0tIHNzNk1GOEhKd2VnTENLUW1ITHFN
            SG5laS9kTGJNWVlNZ3hZcVNQbno1U3cKL7cOjeI5Rd8l59r5hCONliOaCO3OkRff
            DjoCsjOvQw2iHBZ54xMC4oR2UTXSb2rox09QuTWAOM30gd6NCJ0eig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T20:41:31Z"
    mac: ENC[AES256_GCM,data:1nXK6k5xRyHKwuZJtmuI9ADL3MfJW5gZ/XbluqIKytSDkLVV+1zpZb15jQ0rW8i53JkrNfjyOh5aN1zPrqStcIPwA94Mr517z1F4ZHhu2UVp8SbWRfrw5/EG54XXoE7/J50O14hq1hNsVvYZ7P6gmRARaNMJBN4qBZfq4NsAXLw=,iv:ihfiNk6e474tt3L35PdRDWyGRTOVAFctXKsUM3WyVyQ=,tag:Vy5B5TAOuj/WJDaiUSNysA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
