apiVersion: ENC[AES256_GCM,data:EWM=,iv:jruABABf+ZZFidUryHXnom5sp6BwZPuc4764bP5ED3w=,tag:xQMF590C5GNM6hjF6/ApbA==,type:str]
kind: ENC[AES256_GCM,data:JeNGw5mf,iv:fWfLnxEiFvzGdi5Lxh51J3juCpxnkfFXSrYaCvvhnyM=,tag:RRNHaOPFhTP8q1Lx0AzDdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xt7YIVekFQIYnf8TZYGkscFE,iv:J6/rL8WpExkkM7yELraH6xLluCvKQHc2t2e/A28p5Y4=,tag:kvIwdAeGefWBXf9D8ZH/RA==,type:str]
    namespace: ENC[AES256_GCM,data:UW3v3SCChBl8vCs=,iv:9NLRMYi1lLhOznV06N9vA2HEeezWTu8bk8pORmArB08=,tag:TvfvoBEZ8JcGIeq1eTFS8g==,type:str]
type: ENC[AES256_GCM,data:bcardKz9,iv:HPuoOItzumhX0tlFlqoGbsYGbtz/PRqK3+VSHf7JQ58=,tag:gFGrO1zfI7iGJ6z47V8WNA==,type:str]
stringData:
    MD_DB_DRIVER: ENC[AES256_GCM,data:kOOb3wuuvH4=,iv:IOuzd/D6blydBvVt2RUeaNY5BfZetO5RpsEcXC4STA0=,tag:uNW3ZyrEzCt4AGgxftZm9w==,type:str]
    MD_DB_DSN: ENC[AES256_GCM,data:4pdG7s7xF+cyGooNaoi5m/b/shRQYlMnazb95LuHP+BEPskgv5N+ZVvOEORhHe8XPLuI3ZXfmxoUFiowhmUBcdxh8saNdNhZZZ9gINp17A0Ozfp4Eepq4YQ/6exhi6x0,iv:5zUK7kR0xGuuTU4c8K/M6CGuU1UsDTQlVEf/6jjLM2Y=,tag:3duo5hQLGtuVuIm2qtQp9A==,type:str]
sops:
    age:
        - recipient: age13ky20ttewhjkjncjkj3xk4ngah6luurk7xu83p6w7f9z4r49js9qk2t3w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVG1lRkxFcmtTR2F4TzNN
            WnJpM2l5bk1EMUIvWFowRG1ZVFlGUWw2anhrClJjbFBvSkc2a0xUNVFmMUEzS0RP
            dmNqcVNzSEo5VE1kNUwxWXpYR0o5RTgKLS0tIFd4VkIwOFJFdEJYdUxhQTdZU2lj
            ekRMUFgvWTdJWTl1NzBrUllSbDYxRjAK718Kppd/e/GSPkEo33+b824dlDZCyrRW
            CVwyEhEtv1lI0r1TCkRD4zvckKEE04jallHAHCkLsTrt6K/oFtf54w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T20:41:31Z"
    mac: ENC[AES256_GCM,data:xn5j1U343Mk05SVPMl24RIz812sbegWKwY5OFEUHW4CBypxPcML7uaQkgN4z/5VBxCpKXMW0ZprN+ZSmjwTJZGYREk/g4LuSfZirKM7VoMgiDz0hoZx/AiAOIXHReaHFtr91DjheZO8Z8wZ9CrPT7G14mndHzlE89npXvDAWP8c=,iv:iNJ0QCP23cuTkw4CbwHk9DT2EonZNhE9rv+aChk3bss=,tag:hHaQRq3/fUULqtVtqqCJcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
