apiVersion: ENC[AES256_GCM,data:wXM=,iv:SZyoBpcolQKfoPQt4IoAC2o9D4uZJiJpkpcysKdiupw=,tag:VC5aik6r7A3x45+LKjv55Q==,type:str]
kind: ENC[AES256_GCM,data:b+1B/nsJ,iv:PjUBzj2xYiv1frkce5MgOi4sQ/pm8ip0D4pi2oAQJio=,tag:/9WYYq973X60vhTYMS2z0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dycPKBlv0lDaFHGoOzoUYY8BHxqO4bI=,iv:b7uA3t6g3nvyiED6Atl7K0XFUjO5qWGpY8p9r4U94Uc=,tag:uFhJhE8uNmHEP7Rb2ifM7Q==,type:str]
    namespace: ENC[AES256_GCM,data:ob98Ml6wwgl5bEk=,iv:ybm2Hz1Nx1yNWWoMZ47G5La/tk015AWvqLnUAcMWGZQ=,tag:s1ecdIJQnNC0CRNV8H2sLw==,type:str]
type: ENC[AES256_GCM,data:JFoNyrzf,iv:6A13Gi/mCri9VY+cNMv5zaB1DUsU9pXvNmp0Ct8d9dU=,tag:k2A0iamVt8da8UBPs8fdwg==,type:str]
stringData:
    WEB_APP_BASE_URL: ENC[AES256_GCM,data:hRX6ojEqKfFEID6T5SwqcKdrubfTuSXwGDIRTA==,iv:HDpLZkdSZAg2hyugUgowlrLqdRx+dBg1H6prYueZ5ag=,tag:kxHnVCsn9eoccU6W6h85Cw==,type:str]
    GITHUB_OAUTH_REDIRECT_URL: ENC[AES256_GCM,data:H7D0joemRyWm9Ero5A219uU5j7xTzfqHz4GG0wXj8y0r3dVPqkFpMRAf,iv:WV3i8IRDrBALLz90UcnqvydN4EztFgl0LKsMyPG/Lco=,tag:OSXlDwHnkwwR3xfj9b3RYw==,type:str]
    GITHUB_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:s+eioUrG5lwmC7GhQef2f6rfRd0=,iv:fiozPLYwBhnHcxZvMmKO2ZYWMFl+HwrbMnMQPhTKu1E=,tag:2kbz1UGPHPG6pwh/QgWo5w==,type:str]
    GITHUB_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3xpUZo9Ga3/WQMDsLobpFo5qCXaAZVpDpIvALOOYOkLY4KJ8Ib9sMA==,iv:Qj6JuCa8N5KdhGiSbExCSgLsFFlNynkqTzPjkroTweY=,tag:PeOcHCuEsDvBzQLAUhkt8Q==,type:str]
    #ENC[AES256_GCM,data:y1bppcJh+KP5cMKAWi9ww/OMPGCl4tKDj5OxxcoWuH9McN2rIw==,iv:qMBYusXSwaVtH5TJZc7dImQLeOg3o9RuWZosqdZ93j8=,tag:vVAP4gsguLCphiOFpt1Adw==,type:comment]
    GITHUB_API_TOKEN: ENC[AES256_GCM,data:HEZdajyGn50RyO4WBAT+JKbpToah2v/FdzsY4eFaRvGgDz5RDDkERg==,iv:R7t7vud0Qo+BpDH7g2u7o01zpFtPtl4olcrDoZ8CanM=,tag:ZXieDap/NsrTnyO8kZ9dRg==,type:str]
    SESSION_COOKIE_NAME: ENC[AES256_GCM,data:Vw8kcd0bq9T+jA==,iv:vkXKiWyDBI8/dO486r8BUbElCs//KYiN3+kDvOpZqB8=,tag:hw6xTokJRiSchsHnzCa97Q==,type:str]
    SESSION_COOKIE_DOMAIN: ENC[AES256_GCM,data:iWsL8QEzaejHJeMSPhqXdZLqDyA=,iv:562pJW3Hh+yidsad2KdGwzbAnKo0kjYl5fKplHONE/o=,tag:aBQw3rPgHT/WZHcAbYkr5A==,type:str]
    SESSION_COOKIE_SECURE: ENC[AES256_GCM,data:APiMWQ==,iv:i/sltfpOD4Vf4CoCQtA8xYnqYBfiHijMXjpWuvnxmx4=,tag:3sboHbIXMqordceTYIuP9Q==,type:str]
sops:
    age:
        - recipient: age13ky20ttewhjkjncjkj3xk4ngah6luurk7xu83p6w7f9z4r49js9qk2t3w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM296SFcyczQ2eEN2NXZj
            Ym11R2tYNU9sbmRzbEpic1ZIc05oTlFwYkdNCm1td0tKakFldW1UcjJ4NWpjU2NC
            LzF6Q1BHeHJ4Zm1EUFBvUXhRY3p2WlUKLS0tIEwzUmVWa3Z0aGV2M3FBQTBYcEZ2
            VEtlbWJuRHZIN1I0MjhsaXJYVTd5R0kKpz9Sah938Dz0tXT2MGDq6pk+FuEt72F1
            qxsjDq5LxoZL+Ub5B4M0bDqAw6VquQlV1Q7MIwQZgjh3ZJcgOLm+cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T17:14:53Z"
    mac: ENC[AES256_GCM,data:kkDfNpFTVG/L2DCH87JuLa89GJtQtXmYo9y39RofSY+rUcXDj7DbbznbnmnU4zmpXpLyEcksulJjkAEpU0W8sugbw6Hz124jC7Mc8xZWnAaoLptSIfaJpk6JRrmXEbePbxg0fCYHdzs4UTffaGHPT95g/c2c70HyTruRc9TGRzQ=,iv:jL0Xiy/e+6+AOw2vdgmiXwestLp9WRw0A0e3k5YPAwo=,tag:fDLva4tQkszrYSbUnImkaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
